.DEFAULT_GOAL := graphics

clean:
	rm -f graphics.bin

pixels:
	nasm pixels.asm -f bin -o pixels.bin

colors:
	nasm colors.asm -f bin -o colors.bin

animation:
	nasm animation.asm -f bin -o animation.bin
